apiVersion: 1

datasources:
  - name: PostgreSQL-Joomla
    uid: postgres-joomla
    type: postgres
    access: proxy
    url: database:5432
    user: $POSTGRES_USER
    isDefault: true
    editable: true
    jsonData:
      database: $POSTGRES_DB
      sslmode: "disable"
      postgresVersion: 1600
      timescaledb: false
    secureJsonData:
      password: $POSTGRES_PASSWORD
